### ISSUE TITLE
Clones and Roles

### ISSUE THREAD

**Issue by fkw** [Rocket-CDS/RocketContentAPI#5]
Clones :
Enhancements :
- Display AppTheme that is used next to the module title, to better identify (works also for the roles)
- Don't exit after cloning/saving

Roles :
We miss the checkbox "Don't apply to satellite module" that we use to have on NB-Mod

**Comment by leedavi** [comment]
This shodl be on : https://github.com/Rocket-CDS/DNNrocket

**Comment by fkw** [comment]
Permissions and giving access to Manager to all modules :
**We are still missing the checkbox "Ignore satellite module"**

**Comment by leedavi** [comment]
This is not required.  The satellite module edit is hidden and if they edit through DNN the user edits the correct data module.
